name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare for GitHub Pages
        uses: actions/configure-pages@v5
      - uses: actions/checkout@v4
      - name: Clone satro
        run: git clone https://github.com/sakkyoi/satro
      - name: Copy content to satro
        run: |
          # contents
          cp -r ./announcement ./satro/src/content
          cp -r ./footer ./satro/src/content
          cp -r ./article ./satro/src/content
          cp -r ./image ./satro/src/content

          # public (blog thumbnail, favicon)
          cp -r ./public ./satro
      - uses: actions/upload-artifact@master
        with:
          name: satro
          path: ./satro
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/download-artifact@master
        with:
          name: satro
          path: ./
      - name: Build
        run: |
          npm install
          npm run build
        env:
          SITE_URL: ${{ vars.SITE_URL || 'http://localhost' }}
          SITE_TITLE: ${{ vars.SITE_TITLE }}
          SITE_DESCRIPTION: ${{ vars.SITE_DESCRIPTION }}
          SITE_LANG: ${{ vars.SITE_LANG }}
      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        